default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %> 
  host: <%= ENV['RDS_ENDPOINT'] %>

development:
  <<: *default
  # database: db/development.sqlite3 変更
  database: Alcohol_development

test:
  <<: *default
  # database: db/test.sqlite3 変更
  database: Alcohol_test
  host: 127.0.0.1

production:
  <<: *default
  # database: db/production.sqlite3 変更
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>  # 追加